---
title: "TR14 assembly comparison"
author: "Madalina Giurgiu"
date: "5/2/2023"
output:
  html_document:
    toc: yes
    keep_tex: yes
  # pdf_document:
  #   toc: yes
params:
  root: /Users/madag/Projects/PhD/github/decoil-paper/celllines/tr14
---

```{r setup, echo=FALSE, message = FALSE, warning=FALSE}
knitr::opts_chunk$set(fig.width=15, out.width="100%", fig.height=8, out.height="100%")

library(pafr)
library(ggplot2)
library(gridExtra)

setwd(params$root)

```


Pairwise comparison between decoil, shasta and published TR14 breakpoints, against hg38:

```{r echo=FALSE}

setwd(params$root)
paffile1 <- "hg38_decoil.paf"
ali <- read_paf(paffile1)
p1 <- dotplot(ali, label_seqs=TRUE, alignment_colour="black", ylab="hg38", xlab="decoil")  + theme_bw()

paffile2 <- "hg38_shasta.paf"
ali <- read_paf(paffile2)
p2 <- dotplot(ali, label_seqs=TRUE, alignment_colour="black", ylab="hg38", xlab="shasta")  + theme_bw()

paffile3 <- "hg38_paper.paf"
ali <- read_paf(paffile3)
p3 <- dotplot(ali, label_seqs=TRUE, alignment_colour="black", ylab="hg38", xlab="hung_etal_2021")  + theme_bw()


grid.arrange(p1, p2, p3, nrow=1)
```

Pairwise comparison between decoil, shasta against published TR14 breakpoints:

```{r, echo=FALSE, message = FALSE, include=FALSE, warning=FALSE}

paffile1 <- "paper_decoil.paf"
ali <- read_paf(paffile1)
p1 <- dotplot(ali, label_seqs=TRUE, alignment_colour="black", ylab="hung_etal_2021", xlab="decoil")  + theme_bw()

paffile2 <- "paper_shasta.paf"
ali <- read_paf(paffile2)
p2 <- dotplot(ali, label_seqs=TRUE, alignment_colour="black", ylab="hung_etal_2021", xlab="shasta")  + theme_bw()

grid.arrange(p1, p2, nrow=1)

```

Compare decoil and shasta:

```{r, echo=FALSE, message = FALSE, warning=FALSE}

paffile2 <- "shasta_decoil.paf"
ali <- read_paf(paffile2)
p2 <- dotplot(ali, label_seqs=TRUE, alignment_colour="black", ylab="shasta", xlab="decoil")  + theme_bw()

p2
```